chore: Remove rpm release package
Since:
rpm: This software does not run on macOS versions older than Ventura.
Error: rpm: An unsatisfied requirement failed this build.
Error: Process completed with exit code 1.

GitHub not provide Ventura